// <auto-generated />
using BookCollection.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BookCollection.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180304215858_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BookCollection.Core.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("BirthPlace");

                    b.Property<int>("BookCollectionId");

                    b.Property<DateTime>("DeathDate");

                    b.Property<string>("DeathPlace");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleInitial");

                    b.Property<string>("Pseudonym");

                    b.Property<string>("WebsiteLink");

                    b.Property<string>("WikipediaLink");

                    b.HasKey("AuthorId");

                    b.HasIndex("BookCollectionId");

                    b.ToTable("Author");
                });

            modelBuilder.Entity("BookCollection.Core.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BookFormatId");

                    b.Property<int>("BookGenreId");

                    b.Property<int>("CollectionId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Dewey");

                    b.Property<string>("Isbn");

                    b.Property<string>("LocClassification");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("NumberOfPages");

                    b.Property<string>("Plot");

                    b.Property<string>("Publisher");

                    b.Property<DateTime>("PublisherDate");

                    b.Property<string>("SubTitle");

                    b.Property<string>("Title");

                    b.HasKey("BookId");

                    b.HasIndex("BookFormatId");

                    b.HasIndex("BookGenreId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("BookCollection.Core.BookAuthor", b =>
                {
                    b.Property<int>("BookId");

                    b.Property<int>("AuthorId");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthor");
                });

            modelBuilder.Entity("BookCollection.Core.BookFormat", b =>
                {
                    b.Property<int>("BookFormatId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Format");

                    b.HasKey("BookFormatId");

                    b.ToTable("BookFormat");
                });

            modelBuilder.Entity("BookCollection.Core.BookGenre", b =>
                {
                    b.Property<int>("BookGenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre");

                    b.HasKey("BookGenreId");

                    b.ToTable("BookGenre");
                });

            modelBuilder.Entity("BookCollection.Core.BooksCollection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CollectionName");

                    b.Property<int>("UserId");

                    b.HasKey("CollectionId");

                    b.HasIndex("UserId");

                    b.ToTable("BookCollection");
                });

            modelBuilder.Entity("BookCollection.Core.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleInitial");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BookCollection.Core.Author", b =>
                {
                    b.HasOne("BookCollection.Core.BooksCollection", "BooksCollection")
                        .WithMany("Authors")
                        .HasForeignKey("BookCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookCollection.Core.Book", b =>
                {
                    b.HasOne("BookCollection.Core.BookFormat", "BookFormat")
                        .WithMany("Books")
                        .HasForeignKey("BookFormatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookCollection.Core.BookGenre", "BookGenre")
                        .WithMany("Books")
                        .HasForeignKey("BookGenreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookCollection.Core.BooksCollection", "Collection")
                        .WithMany("Books")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookCollection.Core.BookAuthor", b =>
                {
                    b.HasOne("BookCollection.Core.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BookCollection.Core.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BookCollection.Core.BooksCollection", b =>
                {
                    b.HasOne("BookCollection.Core.User", "User")
                        .WithMany("BookCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
